from typing import Protocol

from ..models import BrokerOrder, OrderCommand, PortfolioState


class Broker(Protocol):
    async def snapshot(self) -> PortfolioState: ...
    async def submit(self, command: OrderCommand) -> BrokerOrder: ...
    async def cancel(self, broker_id: str) -> None: ...
    async def close(self) -> None: ...
